### ISSUE TITLE
Windows - wrong input - error

### ISSUE THREAD

**Issue by Berndinox** [knative/client#1172]
### Bug report

When writting a wrong command:
```
PS C:\Users\Bernd> kn services listr
Error: unknown sub-command 'listr' for 'kn service'. Available sub-commands: create, delete, describe, export, list, update
panic: regexp: Compile(`'(C:\Windows\system32\kn.exe\s.+?)'`): error parsing regexp: invalid escape sequence: `\k`

goroutine 1 [running]:
regexp.MustCompile(0xc0006b6cc0, 0x23, 0xc000163ec0)
        /root/.gvm/gos/go1.14.12/src/regexp/regexp.go:311 +0x159
main.extractCommandPathFromErrorMessage(0xc0000f8800, 0x74, 0xc00009e120, 0x1a, 0xc000163f00, 0x1)
        /home/prow/go/src/knative.dev/client/cmd/kn/main.go:190 +0xab
main.printError(0x1a325a0, 0xc00057f760)
        /home/prow/go/src/knative.dev/client/cmd/kn/main.go:182 +0x17a
main.main()
        /home/prow/go/src/knative.dev/client/cmd/kn/main.go:40 +0xa0
```

### Expected behavior

A more "readbale" message!

### Steps to reproduce the problem

Windows 10 

### kn version

```
kn version
Version:      v0.18.4
Build Date:   2020-11-26 07:38:41
Git Revision: 4e09c152
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.18.0)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.18.0)
  - eventing.knative.dev/v1beta1 (knative-eventing v0.18.0)

```

**Comment by navidshaikh** [comment]
thanks for the report @Berndinox !

We try to parse the sub-string `'kn service'` from the following error message for a follow up tip (`Run 'kn service --help' for usage`).
```
Error: unknown sub-command 'listr' for 'kn service'. Available sub-commands: create, delete, describe, export, list, update
```
however, we're using `os.Args[0]` to grab the `kn` string to match the pattern, which on Windows platform is expanding to its absolute path (`C:\Windows\system32\kn.exe`) and the `\k` collides with the regexp expressions. See the formed pattern below:
```
panic: regexp: Compile(`'(C:\Windows\system32\kn.exe\s.+?)'`): error parsing regexp: invalid escape sequence: `\k`
```

The solution is to simply use `"kn"` string to match the required among error message.

**Comment by rhuss** [comment]
fwiw, there should be also an option for regexp to quote the string, instead of using it directly.
