### ISSUE TITLE
service creation UT w/o `--async` fails with NPE

### ISSUE THREAD

**Issue by maximilien** [knative/client#632]
## In what area(s)?

Unit tests

Classifications:
> /kind bug

## What version of Knative Client?

```bash
➜  client git:(issue606) ✗ ./kn version
Using kn config file: /Users/maximilien/.kn/config.yaml
Version:      v20200203-local-00b6c84-dirty
Build Date:   2020-02-03 22:20:55
Git Revision: 00b6c84
Supported APIs:
* Serving
  - serving.knative.dev/v1alpha1 (knative-serving v0.12.0)
* Eventing
  - sources.eventing.knative.dev/v1alpha1 (knative-eventing v0.12.0)
  - eventing.knative.dev/v1alpha1 (knative-eventing v0.12.0)
```

## What version of Knative Serving running on your cluster?

> 0.12.0

## Expected Behavior

The following test should pass.

```go
func TestServiceCreateNoAsync(t *testing.T) {
	action, _, _, err := fakeServiceCreate([]string{
		"service", "create", "foo", "--image", "gcr.io/foo/bar:baz"}, false, false)

	if err != nil {
		t.Fatal(err)
	} else if !action.Matches("create", "services") {
		t.Fatalf("Bad action %v", action)
	}
}
```

## Actual Behavior

Test fails with stack trace:

```go
➜  client git:(issue606) ✗ go test ./pkg/kn/commands/service -test.v -run TestServiceCreateNoAsync
=== RUN   TestServiceCreateNoAsync
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x18eb67a]

goroutine 82 [running]:
k8s.io/client-go/rest.(*RESTClient).Verb(0x0, 0x25b6285, 0x3, 0x2)
	/Users/maximilien/go/pkg/mod/k8s.io/client-go@v0.16.4/rest/client.go:222 +0x3a
k8s.io/client-go/rest.(*RESTClient).Get(0x0, 0x1000000000000)
	/Users/maximilien/go/pkg/mod/k8s.io/client-go@v0.16.4/rest/client.go:247 +0x40
knative.dev/client/pkg/wait.nativePoll.func1(0xc0004ebf78, 0xc0004ebeb0, 0x2, 0x0)
	/Users/maximilien/github/knative-client/src/github.com/knative/client/pkg/wait/poll_watcher.go:176 +0x83
knative.dev/client/pkg/wait.(*pollingWatcher).start.func1(0xc0006cc100)
	/Users/maximilien/github/knative-client/src/github.com/knative/client/pkg/wait/poll_watcher.go:100 +0x1c3
created by knative.dev/client/pkg/wait.(*pollingWatcher).start
	/Users/maximilien/github/knative-client/src/github.com/knative/client/pkg/wait/poll_watcher.go:89 +0x5a
FAIL	knative.dev/client/pkg/kn/commands/service	4.772s
FAIL
```

If I add `--async` to `fakeServiceCreate(...)` call then it passes. So the passing test is:

```go
func TestServiceCreateNoAsync(t *testing.T) {
	action, _, _, err := fakeServiceCreate([]string{
		"service", "create", "foo", "--image", "gcr.io/foo/bar:baz", "--async"}, false, false)

	if err != nil {
		t.Fatal(err)
	} else if !action.Matches("create", "services") {
		t.Fatalf("Bad action %v", action)
	}
}
```

## Steps to Reproduce the Problem

Add test case above (w/o `--async`) and run it as part of `./hack/build-sh` or run it by itself with:

`go test ./pkg/kn/commands/service -test.v -run TestServiceCreateNoAsync`

**Comment by navidshaikh** [comment]
`fakeServiceCreate` takes arg `sync bool`; pass `true` if not using `--async` flag
```
func fakeServiceCreate(args []string, withExistingService bool, sync bool) (
```

Adding the test case as you wrote in issue with `true` value for `sync` to `fakeServiceCreate` call
```
✗ git -P diff                                                                     
diff --git a/pkg/kn/commands/service/create_test.go b/pkg/kn/commands/service/create_test.go
index e9ad1557..0b4ace2e 100644
--- a/pkg/kn/commands/service/create_test.go
+++ b/pkg/kn/commands/service/create_test.go
@@ -493,3 +493,14 @@ func TestServiceCreateWithServiceAccountName(t *testing.T) {
 		t.Fatalf("wrong service account name:%v", template.Spec.ServiceAccountName)
 	}
 }
+
+func TestServiceCreateNoAsync(t *testing.T) {
+	action, _, _, err := fakeServiceCreate([]string{
+		"service", "create", "foo", "--image", "gcr.io/foo/bar:baz"}, false, true)
+
+	if err != nil {
+		t.Fatal(err)
+	} else if !action.Matches("create", "services") {
+		t.Fatalf("Bad action %v", action)
+	}
+}

➜ go test ./pkg/kn/commands/service -count=1 -test.v -run TestServiceCreateNoAsync


=== RUN   TestServiceCreateNoAsync
--- PASS: TestServiceCreateNoAsync (0.00s)
PASS
ok  	knative.dev/client/pkg/kn/commands/service	0.029s
```

**Comment by maximilien** [comment]
Hmm, thanks @navidshaikh. Kind of begs the question why that `bool` param is needed when it can be inferred from other args? Is it because you want to test the cases when the args differ? Curious.

**Comment by navidshaikh** [comment]
@maximilien :

> why that bool param is needed when it can be inferred from other args?

Agreed, it can be inferred from the args.

Re-opening the issue if you want to improve this.

**Comment by maximilien** [comment]
OK, let me take a pass after I am done with #606
