### ISSUE TITLE
`kn source ping describe foo` panics when Sink uses URI instead of Ref

### ISSUE THREAD

**Issue by jchesterpivotal** [knative/client#847]
### Bug report

When using `kn` to describe a PingSource, it will panic due to a nil pointer error if the Sink was defined with a URI instead of a Ref.

I believe the bug lies [in this code](https://github.com/knative/client/blob/0df54bc500ad960568e5d00285d3f112b9db665e/pkg/kn/commands/source/ping/describe.go#L93-L94):

```
	subWriter.WriteAttribute("Name", sink.Ref.Name)
	subWriter.WriteAttribute("Namespace", sink.Ref.Namespace)
```

Specifically, the code assumes that `sink.Ref` is not nil. Interestingly the code following guards for nil-ness:

```
	ref := sink.Ref
	if ref != nil {
		subWriter.WriteAttribute("Resource", fmt.Sprintf("%s (%s)", sink.Ref.Kind, sink.Ref.APIVersion))
	}
```

### Expected behavior

I expect that `kn source ping describe` does not have an error when inspecting a Sink that uses a URI rather than a Ref.

### Steps to reproduce the problem

```
$ kn source ping create example --sink https://example.com/sink
Ping source 'example' created in namespace 'default'.

$ kn source ping describe ping-player
Name:         example
Namespace:    default
Annotations:  [redacted]
Age:          2m
Schedule:     * * * * *
Data:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1fa81b9]

goroutine 1 [running]:
knative.dev/client/pkg/kn/commands/source/ping.writeSink(0x24f8c60, 0xc0005b6b70, 0xc00026cc78)
	/home/prow/go/src/knative.dev/client/pkg/kn/commands/source/ping/describe.go:93 +0x89
knative.dev/client/pkg/kn/commands/source/ping.NewPingDescribeCommand.func1(0xc00024cdc0, 0xc0003f61a0, 0x1, 0x1, 0x0, 0x0)
	/home/prow/go/src/knative.dev/client/pkg/kn/commands/source/ping/describe.go:69 +0x1f1
github.com/spf13/cobra.(*Command).execute(0xc00024cdc0, 0xc0003f6170, 0x1, 0x1, 0xc00024cdc0, 0xc0003f6170)
	/home/prow/go/src/knative.dev/client/vendor/github.com/spf13/cobra/command.go:832 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001722c0, 0x161043a4a23d1638, 0x3049d20, 0xc00001df10)
	/home/prow/go/src/knative.dev/client/vendor/github.com/spf13/cobra/command.go:920 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prow/go/src/knative.dev/client/vendor/github.com/spf13/cobra/command.go:870
main.main()
	/home/prow/go/src/knative.dev/client/cmd/kn/main.go:36 +0xc8
```

### kn version

```
Version:      v0.14.0
Build Date:   2020-04-22 08:56:32
Git Revision: c41e9fd
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.14.0)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.14.1)
  - eventing.knative.dev/v1alpha1 (knative-eventing v0.14.1)
```

### Knative (serving/eventing) version

v0.14.0.

**Comment by rhuss** [comment]
Thanks for the report, good find !

This should be easy to fix.
